databases:
  - name: jai-maa-bhadrakali-db
    plan: free

services:
  - type: web
    name: jai-maa-bhadrakali-studio
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn studio.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "jai-maa-studio.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://jai-maa-studio.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: jai-maa-bhadrakali-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
