# Generated by Django 5.2.5 on 2026-04-03 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('prewedding', 'Pre Wedding'), ('candid', 'Candid'), ('fineart', 'Fine Art'), ('video', 'Video')], default='prewedding', max_length=50),
        ),
    ]
