# Generated by Django 5.2.5 on 2026-04-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_booking_created_at_gallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('prewedding', 'Pre Wedding'), ('candid', 'Candid'), ('fineart', 'Fine Art'), ('video', 'Video'), ('traditional', 'Traditional Video'), ('cinematic', 'Cinematic Highlights'), ('katha', 'Live Katha Streaming'), ('album', 'Wedding Album Design')], default='prewedding', max_length=50),
        ),
    ]
