# Generated by Django 5.2.5 on 2026-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chatdata_unknownquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
