# Generated by Django 5.2.5 on 2026-04-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
