# Generated by Django 5.2.5 on 2026-05-02 19:15

from datetime import datetime

from django.db import migrations, models


def backfill_event_date_value(apps, schema_editor):
    Booking = apps.get_model('main', 'Booking')
    formats = ("%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%d %B %Y", "%d %b %Y")

    for booking in Booking.objects.filter(event_date_value__isnull=True):
        raw_date = (booking.event_date or "").strip()
        for date_format in formats:
            try:
                booking.event_date_value = datetime.strptime(raw_date, date_format).date()
                booking.save(update_fields=["event_date_value"])
                break
            except ValueError:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_booking_notes_booking_status_alter_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.RunPython(backfill_event_date_value, migrations.RunPython.noop),
    ]
