# Generated by Django 5.2.5 on 2026-05-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_booking_advance_amount_booking_event_date_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatdata',
            options={'ordering': ['priority', 'id']},
        ),
        migrations.AddField(
            model_name='chatdata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatdata',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma or line separated words/phrases that should trigger this answer.'),
        ),
        migrations.AddField(
            model_name='chatdata',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Lower number is checked first.'),
        ),
    ]
