# Generated by Django 5.2.5 on 2026-05-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_chatdata_options_chatdata_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call'), ('youtube', 'YouTube'), ('instagram', 'Instagram')], max_length=20)),
                ('page', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_label', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Add one package feature per line.')),
                ('cta_label', models.CharField(default='Choose Package', max_length=50)),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('highlighted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='lead_source',
            field=models.CharField(blank=True, default='Website', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unknownquestion',
            name='trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
